### PR TITLE
Notebook 4.2 tests

### PR DESCRIPTION
**Pull request by bollwyvl**
Fixes the install of the extension so the tests run. But they fail. But we can worry about that on the main PR.

Also, this adds git_url in `meta.yml`. Just for reproducible builds.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Tests work on OSX. Attempting Windows. :rotating_light:

**Comment by bollwyvl** [comment]
Of course, now having to build notebook conda package on windows. `-c javascript` doesn't have win64... trying with cpcloud's old <1.0 release....

**Comment by bollwyvl** [comment]
Windows build is a bit special. I've gotten _something_ building, but am hitting weird conda errors when trying to install it :(

**Comment by bollwyvl** [comment]
Whew, was just able to get windows nb_anacondacloud working as a user in the development environment.

Proceeding on conda build/test.

**Comment by bollwyvl** [comment]
@malev this builds (and the tests run!) on osx and windows!

The CI will fail, most likely... I'm really hesitant to put a built notebook 4.1+ anywhere :)

**Comment by damianavila** [comment]
> I'm really hesitant to put a built notebook 4.1+ anywhere :)

If we put it somewhere it should be a local build under an user account, for instance malev... if we have to patch the build system to look into that channel, it is OK for me as a temporary workaround, but I would hate to have something called 4.2 or, even worst 5.x, out there, for instance, in our extension space.

**Comment by damianavila** [comment]
Btw, will review during the week...

**Comment by bollwyvl** [comment]
Rather than trying to rebase, going to re-do this with lessons learned from nbpresent.

**Comment by damianavila** [comment]
:tada:

**Pull request closed without merging**
