### PR TITLE
[wip] Support notebook 4.2 beta

### PR DESCRIPTION
**Pull request by bollwyvl**
This is a re-imagining of #20, with new stuff from nbpresent.

### CODE REVIEW

**Comment by bollwyvl** [comment]
I switched over the CI hook to `anaconda-platform`

**Comment by damianavila** [comment]
Quick review, LGTM...

**Comment by bollwyvl** [comment]
Betas are up here:
https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/files?version=1.0.0b2

Had to manually build the OSX and win packages.

Will do betas of all of the other extensions so that I can start doing platform-specific tests, as well as the  metapackage tests .

**Comment by bollwyvl** [comment]
I've brought over the code from nb_conda which matches this regex:

```
var m = /\[(.+)\]$/.exec(kernel_name);
```

This pretty much solves #22, but I am still going to be doing more local testing across the os/py matrix, as well as the unified testing. However, if nothing else shows up, these betas might be the actual releases, minus some changelog.

Betas up here:
https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/files?version=1.0.0b3

**Comment by damianavila** [comment]
> I've brought over the code from nb_conda which matches this regex:

Nice... I think it is the most straightforward path, so :+1:

**Pull request merged**
