### PR TITLE
Cross-platform builds on anconda cloud

### PR DESCRIPTION
**Pull request by bollwyvl**
This hadn't been updated in some time. Let's see how it goes.

### CODE REVIEW

**Comment by damianavila** [comment]
All red... jeje... npm error, it seems...

**Comment by bollwyvl** [comment]
Ha, it worked.

**Comment by bollwyvl** [comment]
- [ ] [win32-py34](https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/builds/16/9) 
  
  ```
  221  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\instructions.py", line 62, in EXTRACT_CMD
  
  222    install.extract(config.pkgs_dirs[0], arg)
  
  223  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\install.py", line 485, in extract
  
  224    t.extractall(path=path)
  
  225  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2072, in extractall
  
  226    self.extract(tarinfo, path)
  
  227  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2109, in extract
  
  228    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  
  229  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2185, in _extract_member
  
  230    self.makefile(tarinfo, targetpath)
  
  231  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2225, in makefile
  
  232    with bltn_open(targetpath, "wb") as target:
  
  233IOError: [Errno 13] Permission denied: u'C:\\Users\\binstar\\Miniconda\\pkgs\\python-3.4.4-2\\DLLs\\_bz2.pyd'
  
  234Internal binstar build error: Could not set up initial build state
  ```

**Comment by bollwyvl** [comment]
- [ ] [win32 py35](https://anaconda.org/anaconda-nb-extensions/nb_anacondacloud/builds/17/10) 

```
Traceback (most recent call last):

1186  File "C:\Users\binstar\Miniconda\Scripts\conda-build-script.py", line 4, in <module>

1187    sys.exit(main())

1188  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 192, in main

1189    args_func(args, p)

1190  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 486, in args_func

1191    args.func(args, p)

1192  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py", line 472, in execute

1193    build.test(m)

1194  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\build.py", line 524, in test

1195    os.makedirs(tmp_dir)

1196  File "C:\Users\binstar\Miniconda\lib\os.py", line 157, in makedirs

1197    mkdir(name, mode)

1198WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\binstar\\Miniconda\\conda-bld\\test-tmp_dir'

1199Exit BINSTAR_BUILD_RESULT=failure
```

**Comment by bollwyvl** [comment]
On my local win64 py27 environment, i am getting npm errors:

```
WARNING:conda.install:Cannot remove, unknown reason: C:\Users\builder\Miniconda27-32\pkgs\.trash\tmp3bvjwt\envs\_build\_
build\Scripts\node_modules\npm\node_modules\node-gyp\node_modules\npmlog\node_modules\gauge\node_modules\lodash.padleft\
node_modules\lodash._createpadding\node_modules\lodash.repeat\package.json
```

No doubt, this is due to the long paths issue, but doesn't apparently cause an issue... but it might be nice to be able to specify a way to get a different trash location...

**Comment by bollwyvl** [comment]
Finally getting somewhere: on windows in the test enviornment, the path is weird and `casperjs` doesn't resolve to `Scripts\casperjs.cmd`.

Adding

```
import platform
IS_WIN = "Windows" in platform.system()


class NBAnacondaCloudTestController(jstest.JSController):
    def __init__():

...
        if IS_WIN:
            self.cmd[0] = "{}.cmd".format(self.cmd[0])
```

seems to do the trick...

**Comment by bollwyvl** [comment]
As discussed, LGTM on the build.

I was able to do local windows 64 builds.

I guess we merge, (optionally) do a new issue for the release `0.1.3`, do the release, build the windows packages locally, then start doing the `dev` tagging thing. Would love to get back to building cool features with this!

**Comment by bollwyvl** [comment]
@malev @damianavila @mmarchetti this looks good to me, and I'd like to see it merged so we can rebase #13 and get some test confidence around the ~~login~~ sign in activity.

**Comment by malev** [comment]
working great in `osx` :+1: to the merge

**Comment by malev** [comment]
@bollwyvl why aren't we merging this?

**Pull request merged**
